Supply ElfDecoder::demangle from this release's os/linux copy
decoder_bsd.cpp carried the 28 body, which calls free() through
permit_forbidden_function -- a header that does not exist here:

  decoder_bsd.cpp:33:10: fatal error:
  'utilities/permitForbiddenFunctions.hpp' file not found

Take the demangle() this release's os/linux/decoder_linux.cpp uses.