Find struct ether_addr on NetBSD
The _ALLBSD_SOURCE branch includes <net/ethernet.h>.  macOS, FreeBSD and
OpenBSD have that header; NetBSD does not, and keeps struct ether_addr
in <net/if_ether.h>:

  NetworkInterface.c:41:10: fatal error: net/ethernet.h: No such file
  or directory

(cherry picked from commit 59867512a8f28531ad1fb94a36dda25183a2dab1)